import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {AuthProvider} from "@/context/AuthContext";
import React from "react";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  // @ts-ignore
  return (
    <html lang="en">
    <AuthProvider>
      <body className={inter.className + ` text-white bg-black h-screen w-screen `}>{children}</body>
    </AuthProvider>
    </html>
  )
}
